@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fi.jakojaannos.riista.vulkan.renderer.particles;

import javax.annotation.ParametersAreNonnullByDefault;

import fi.jakojaannos.riista.utilities.annotation.FieldsAreNonnullByDefault;
import fi.jakojaannos.riista.utilities.annotation.MethodsReturnNonnullByDefault;