@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fi.jakojaannos.konna;

import javax.annotation.ParametersAreNonnullByDefault;

import fi.jakojaannos.roguelite.engine.utilities.annotation.FieldsAreNonnullByDefault;
import fi.jakojaannos.roguelite.engine.utilities.annotation.MethodsReturnNonnullByDefault;