@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fi.jakojaannos.riista.vulkan.application;

import javax.annotation.ParametersAreNonnullByDefault;

import fi.jakojaannos.riista.utilities.annotation.FieldsAreNonnullByDefault;
import fi.jakojaannos.riista.utilities.annotation.MethodsReturnNonnullByDefault;