version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Compile
          command: |
            ./gradlew compileJava
            ./gradlew assemble
      - run:
          name: Run tests
          command: |
            ./gradlew compileTestJava
            ./gradlew check
      - run:
          name: Upload test results to CodeCov
          command: |
            ./gradlew jacocoTestReport jacocoRootReport
            bash <(curl -s https://codecov.io/bash)
      - run:
          name: Save test results to Circle
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  deploy:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-jdk

      - run: gradle dependencies
      - run:
          name: Download windows JDK
          command: |
            mkdir jdk
            cd jdk
            wget https://download.java.net/java/GA/jdk14/076bab302c7b4508975440c56f6cc26a/36/GPL/openjdk-14_windows-x64_bin.zip
            unzip ./openjdk-14_windows-x64_bin.zip -d jdk-windows
            cd ..
      - run:
          name: Build
          command: ./gradlew compileJava assemble
      - run:
          name: Package
          command: TARGET_PLATFORM=windows ./gradlew jlinkZip

      - store_artifacts:
          path: ./launcher/build/image-windows.zip
          destination: 'konna-unstable-win.zip'

workflows:
  version: 2.1
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
