version: 2.1
orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:13-jdk-buster
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Compile
          command: |
            gradle compileJava
            gradle assemble
      - run:
          name: Run tests
          command: |
            gradle compileTestJava 
            gradle check
      - run:
          name: Upload test results to CodeCov
          command: |
            gradle jacocoTestReport jacocoRootReport
            bash <(curl -s https://codecov.io/bash)
      - run:
          name: Save test results to Circle
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  deploy:
    executor: win/default

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Build
          command: ./gradlew.bat compileJava assemble
          shell: bash.exe
      - run:
          name: Package
          command: ./gradlew.bat jlinkZip
          shell: bash.exe

      - store_artifacts:
          path: ./launcher/build/image.zip
          destination: 'konna-unstable.zip'

workflows:
  version: 2.1
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
