@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package fi.jakojaannos.roguelite.engine.utilities.assertions.junitextension;

import javax.annotation.ParametersAreNonnullByDefault;

import fi.jakojaannos.roguelite.engine.utilities.annotation.FieldsAreNonnullByDefault;
import fi.jakojaannos.roguelite.engine.utilities.annotation.MethodsReturnNonnullByDefault;
