package fi.jakojaannos.riista.vulkan.internal.types;

import fi.jakojaannos.riista.utilities.BitFlags;

import static org.lwjgl.vulkan.VK11.*;

public enum VkFormatFeatureFlags implements BitFlags {
    SAMPLED_IMAGE_BIT(VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT),
    STORAGE_IMAGE_BIT(VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT),
    STORAGE_IMAGE_ATOMIC_BIT(VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT),
    UNIFORM_TEXEL_BUFFER_BIT(VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT),
    STORAGE_TEXEL_BUFFER_BIT(VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT),
    STORAGE_TEXEL_BUFFER_ATOMIC_BIT(VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT),
    VERTEX_BUFFER_BIT(VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT),
    COLOR_ATTACHMENT_BIT(VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT),
    COLOR_ATTACHMENT_BLEND_BIT(VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT),
    DEPTH_STENCIL_ATTACHMENT_BIT(VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT),
    BLIT_SRC_BIT(VK_FORMAT_FEATURE_BLIT_SRC_BIT),
    BLIT_DST_BIT(VK_FORMAT_FEATURE_BLIT_DST_BIT),
    SAMPLED_IMAGE_FILTER_LINEAR_BIT(VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT);

    private final int mask;

    @Override
    public int getMask() {
        return this.mask;
    }

    VkFormatFeatureFlags(final int mask) {
        this.mask = mask;
    }
}
