@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
@FieldsAreNonnullByDefault
package fi.jakojaannos.roguelite.engine.input;

import javax.annotation.ParametersAreNonnullByDefault;

import fi.jakojaannos.riista.utilities.annotation.FieldsAreNonnullByDefault;
import fi.jakojaannos.riista.utilities.annotation.MethodsReturnNonnullByDefault;