@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fi.jakojaannos.riista.view;

import javax.annotation.ParametersAreNonnullByDefault;

import fi.jakojaannos.riista.utilities.annotation.FieldsAreNonnullByDefault;
import fi.jakojaannos.riista.utilities.annotation.MethodsReturnNonnullByDefault;