package fi.jakojaannos.konna.engine.vulkan.types;

import static org.lwjgl.vulkan.VK10.*;

public enum VkPrimitiveTopology {
    POINT_LIST(VK_PRIMITIVE_TOPOLOGY_POINT_LIST),
    LINE_LIST(VK_PRIMITIVE_TOPOLOGY_LINE_LIST),
    LINE_STRIP(VK_PRIMITIVE_TOPOLOGY_LINE_STRIP),
    TRIANGLE_LIST(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST),
    TRIANGLE_STRIP(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP),
    TRIANGLE_FAN(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN),
    LINE_LIST_WITH_ADJACENCY(VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY),
    LINE_STRIP_WITH_ADJACENCY(VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY),
    TRIANGLE_LIST_WITH_ADJACENCY(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY),
    TRIANGLE_STRIP_WITH_ADJACENCY(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY),
    PATCH_LIST(VK_PRIMITIVE_TOPOLOGY_PATCH_LIST);

    private final int topology;

    VkPrimitiveTopology(final int topology) {
        this.topology = topology;
    }

    public int asInt() {
        return this.topology;
    }
}
